FROM node:18.19.0

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable

WORKDIR /app
COPY package*.json ./

RUN npm install -g @angular/cli

RUN npm install
COPY . .

CMD ["npm", "test", "--watch=false"]



